### ISSUE TITLE
Curate list of Docker images

### ISSUE THREAD

**Issue by nx10** [childmindresearch/niwrap#118]
- [ ] Find trusted images for each package (preferably first party / by the packages maintainers)
- [ ] Ensure each descriptor in the same package is pointing to the same image (unless there is a good reason to use more than one)

**Comment by kaitj** [comment]
| tool | container | notes |
|--|--|--|
|fsl| brainlife/fsl:6.0.4-patched2 | - couldn't find container from authors |
| |  fnndsc/fsl:6.0.5.1-cuda9.1 | - probably want to avoid a specific version of cuda |
| | vnmd/fsl_6.0.4:20210422 |
| c3d |  https://github.com/pyushkevich/tk-docker | - author of tool, would need to build and distribute container, includes other tools like greedy, cmrep |
| | pyushkevich/itksnap:v3.8.2 | - this is an existing package
| ants | antsx/ants:v2.5.3 | - first-party |

@nx10  - let me know what you think:
*  fsl - a lot of containers from other groups (bch, brainlife, nipreps, neurodesk). I think it probably makes sense to use one of those rather than build / maintain our own. also probably want to avoid a specific version of cuda
* c3d - i think the iksnap one is probably okay. even the tk-docker includes other tools.

**Comment by nx10** [comment]
Thanks!
